#pragma once



typedef enum
{
	FLS_ADDR_MEM_FIRST_RUN_CHECK = 0,

	/*Encoder-------------------*/
	FLS_ADDR_ENC0_RESOLUTION,
	FLS_ADDR_ENC1_RESOLUTION,

	/*Stepper motor-------------*/
	FLS_ADDR_STEPPER_MOTOR_STEPANGLE ,
	FLS_ADDR_STEPPER_MOTOR_MAX_RPM,

	/*DM542T Driver-------------*/
	FLS_ADDR_DM542T_MICROSTEP ,

	/*HB Motor Controller----------*/
	FLS_ADDR_HB_CTRL_CALIBRATION_SPEED,
	FLS_ADDR_HB_CTRL_WAITING_TIMEOUT,
	FLS_ADDR_HB_CTRL_PATH,

	/*STEPPER	Motor Controller----------*/
	//FLS_ADDR_MOTR_CTRL_TYPE,
	FLS_ADDR_STPR_CTRL_CALIBRATION_SPEED,
	FLS_ADDR_STPR_CTRL_WAITING_TIMEOUT,
	FLS_ADDR_STPR_CTRL_PATH,

	/*Motor Safety---------------*/
	FLS_ADDR_MOTR_SAFETY_HOLDING_DUTY,
	FLS_ADDR_MOTR_SAFETY_RUNNING_DUTY,
	FLS_ADDR_MOTR_SAFETY_WAITING_TIME,

	/*PID 0---------------------*/
	FLS_ADDR_PID0_SETPOINT,
	FLS_ADDR_PID0_KP,
	FLS_ADDR_PID0_KI,
	FLS_ADDR_PID0_KD,
	FLS_ADDR_PID0_I_OUT_LIMIT,

	/*PID 1---------------------*/
	FLS_ADDR_PID1_SETPOINT,
	FLS_ADDR_PID1_KP,
	FLS_ADDR_PID1_KI,
	FLS_ADDR_PID1_KD,
	FLS_ADDR_PID1_I_OUT_LIMIT,

	/*Modbus TCP Net info--------*/
	FLS_ADDR_MB_TCPS_PORT,
	FLS_ADDR_MB_TCPS_MAC1,
	FLS_ADDR_MB_TCPS_MAC2,
	FLS_ADDR_MB_TCPS_MAC3,
	FLS_ADDR_MB_TCPS_MAC4,
	FLS_ADDR_MB_TCPS_MAC5,
	FLS_ADDR_MB_TCPS_MAC6,

	FLS_ADDR_MB_TCPS_IP1,
	FLS_ADDR_MB_TCPS_IP2,
	FLS_ADDR_MB_TCPS_IP3,
	FLS_ADDR_MB_TCPS_IP4,

	FLS_ADDR_MB_TCPS_SN1,
	FLS_ADDR_MB_TCPS_SN2,
	FLS_ADDR_MB_TCPS_SN3,
	FLS_ADDR_MB_TCPS_SN4,

	FLS_ADDR_MB_TCPS_GW1,
	FLS_ADDR_MB_TCPS_GW2,
	FLS_ADDR_MB_TCPS_GW3,
	FLS_ADDR_MB_TCPS_GW4,

	FLS_ADDR_MB_TCPS_APPLY_CHANGE,

	/*Modbus RTU Serial Parameters--------*/
	FLS_ADDR_MB_RTU_BAUD,
	FLS_ADDR_MB_RTU_DATA_BIT,
	FLS_ADDR_MB_RTU_STOP_BIT,
	FLS_ADDR_MB_RTU_PARITY,

	FLS_ADDR_MB_RTU_APPLY_CHANGE,


	/*Utilities--------------*/
	FLS_ADDR_DBUG_ENABLE,
	//...
	FLS_ADDR_MAX
} flash_addr_t;
